language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
# command to install dependencies
before_install:
  - make install
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install "django<2"; fi
# command to run tests
script: pytest test_django_image.py
